openapi: 3.1.0
info:
  title: Agents API
  version: 1.0.0
servers:
  - url: https://api.repliers.io
paths:
  /agents:
    post:
      summary: Create an agent
      description: Use this endpoint to create an agent. Each client that you create needs to be associated with an agent, therefore it's necessary to create at least one agent before you start creating clients.
      operationId: create-an-agent
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - fname
                - lname
                - phone
                - email
                - brokerage
                - designation
              properties:
                fname:
                  type: string
                  description: The first name of the agent.
                lname:
                  type: string
                  description: The last name of the agent.
                phone:
                  type: string
                  description: "The mobile phone number of the agent. Must be 11 digits in length.<br/><br/>Regex pattern: <code>^(1)([0-9]{10})$</code>"
                email:
                  type: string
                  description: "The email address of the agent.<br/><br/>Regex pattern: <code>^(([^<>()\\[\\]\\\\.,;:\\s@\"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))</code>"
                brokerage:
                  type: string
                  description: The name of the Brokerage/Office that this agent is registered with.
                designation:
                  type: string
                  description: This agent's designation. For example, "Sales Representative"
                avatar:
                  type: string
                  description: A URL/Path to an avatar/picture of this agent.
                status:
                  type: boolean
                  description: If false, disables all operations for the agent.
                  default: true
                location:
                  properties:
                    latitude:
                      type: string
                      description: A latitude value representing the location of the agent. Required if a value for longitude is provided.
                    longitude:
                      type: string
                      description: A longitude value representing the location of the agent. Required if a value for latitude is specified.
                  required: []
                  type: object
                externalId:
                  type: string
                  description: The externalId is intended for storing agent identifiers from external systems (such as CRMs) for reference purposes.
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
    get:
      summary: Filter agents
      description: Use this endpoint to get a list of agents that you've created. You can filter for specific agents using parameters like email address and first name. If you don't use any filters all agents will be returned.
      operationId: find-agents
      parameters:
        - name: agentId
          in: query
          schema:
            type: integer
            format: int32
        - name: boardId
          in: query
          schema:
            type: integer
            format: int32
        - name: brokerage
          in: query
          schema:
            type: string
        - name: designation
          in: query
          schema:
            type: string
        - name: email
          in: query
          schema:
            type: string
        - name: fname
          in: query
          schema:
            type: string
        - name: lname
          in: query
          schema:
            type: string
        - name: phone
          in: query
          schema:
            type: integer
            format: int32
        - name: status
          in: query
          schema:
            type: boolean
        - name: externalId
          in: query
          description: Filter agents by their identifier from an external system (such as a CRM).
          schema:
            type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
  /agents/{agentId}:
    patch:
      summary: Update an agent
      description: Use this endpoint to update information associated with an agent.
      operationId: update-an-agent
      parameters:
        - name: agentId
          in: path
          schema:
            type: integer
            format: int32
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fname:
                  type: string
                  description: The first name of the agent.
                lname:
                  type: string
                  description: The last name of the agent.
                phone:
                  type: string
                  description: "The mobile phone number of the agent. Must be 11 digits in length.<br/><br/>Regex pattern: <code>^(1)([0-9]{10})$</code>"
                email:
                  type: string
                  description: "The email address of the agent.<br/><br/>Regex pattern: <code>^(([^<>()\\[\\]\\\\.,;:\\s@\"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))</code>"
                brokerage:
                  type: string
                  description: The name of the Brokerage/Office that this agent is registered with.
                designation:
                  type: string
                  description: This agent's designation. For example, "Sales Representative"
                avatar:
                  type: string
                  description: A URL/Path to an avatar/picture of this agent.
                status:
                  type: boolean
                  description: If false, disables all operations for the agent.
                  default: true
                location:
                  properties:
                    latitude:
                      type: string
                      description: A latitude value representing the location of the agent. Required if a value for longitude is provided.
                    longitude:
                      type: string
                      description: A longitude value representing the location of the agent. Required if a value for latitude is specified.
                  required: []
                  type: object
                externalId:
                  type: string
                  description: The externalId is intended for storing agent identifiers from external systems (such as CRMs) for reference purposes.
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
    delete:
      summary: Delete an agent
      description: Use this endpoint to delete an agent. You must specify a new agentId to assign the deleted agent's clients to.
      operationId: delete-an-agent
      parameters:
        - name: agentId
          in: path
          schema:
            type: integer
            format: int32
          required: true
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
    get:
      summary: Get an agent
      description: Use this endpoint to lookup details about a specific agent.
      operationId: get-an-agent
      parameters:
        - name: agentId
          in: path
          schema:
            type: integer
            format: int32
          required: true
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
  /agents/{agentId}/transfer:
    post:
      summary: Transfer an agent's clients
      description: Use this endpoint to transfer all clients from one agent to another.
      operationId: transfer-agents
      parameters:
        - name: agentId
          in: path
          description: The agentId of the agent whose clients will be transferred to another agent.
          schema:
            type: integer
            format: int32
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - newAgentId
              properties:
                newAgentId:
                  type: integer
                  description: The agentId of the new agent who will takeover clients from the previous agent.
                  format: int32
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
