openapi: 3.1.0
info:
  title: Locations API
  description: |
    API for searching, filtering, and retrieving location data across multiple geographical hierarchies.
    Provides endpoints for location querying based on various parameters including geographical boundaries,
    administrative divisions and location types. Supports filtering, pagination, and custom field selection.
  version: 1.0.0
servers:
  - url: https://api.repliers.io
    description: Production server
  - url: https://dev.repliers.io
    description: Development server
paths:
  /nlp:
    post:
      summary: New Prompt
      description: |
        This endpoint translates natural language search queries into structured API requests for the Repliers listings endpoint. For example, the prompt `find me properties in new york`` would be converted to the equivalent API call: https://api.repliers.io/listings?city=New York
      tags:
        - NLP
      parameters:
        - name: nlpVersion
          in: query
          description: NLP Model version
          required: false
          schema:
            type: string
            default: "1"
            enum: ["1", "2", "3"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The natural language prompt to be processed.
                  example: "Find me a condo in toronto with at least 1 bedroom in the annex. It must have underground parking."
                nlpId:
                  type: string
                  description: |
                    Unique identifier to maintain context-aware interactions.
                    When you send a new prompt to the `/nlp` endpoint, the system returns an `nlpId` in the response. This `nlpId` can be included in subsequent prompts to maintain context, allowing the NLP tool to consider both the original and new prompts when generating the API request.
                  example: "d38a5bfc-3e8f-4a00-b9s7a-49fe545fa72b"
                clientId:
                  type: string
                  description: The `clientId` of the client that the NLP prompt is for.
                  example: "12345"
      responses:
        "200":
          description: Successful response with processed data.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/NLPResponseObject"
                  - type: object
                    properties:
                      request:
                        $ref: "#/components/schemas/NLPRequest"
        "400":
          description: Bad Request - Invalid input.
        "500":
          description: Internal Server Error - An error occurred while processing the request.
    get:
      summary: Filter sessions
      description: |
        This endpoint allows you to retrieve all NLP prompts that are associated with a unique `nlpId` session.
      tags:
        - NLP
      parameters:
        - name: nlpId
          in: query
          description: Unique identifier for the NLP session.
          required: false
          schema:
            type: string
        - name: clientId
          in: query
          description: Filter sessions based on the `clientId` to see all NLP sessions associated with a specific client.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successful response with NLP session data.
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "components.yml#/components/schemas/PaginationInfo"
                  - type: object
                    properties:
                      prompts:
                        type: array
                        description: List of NLP prompts and their responses
                        items:
                          allOf:
                            - $ref: "#/components/schemas/NLPResponseObject"
                            - type: object
                              properties:
                                request:
                                  $ref: "#/components/schemas/NLPRequest"
        "500":
          description: Internal Server Error - An error occurred while processing the request.

components:
  schemas:
    NLPResponseObject:
      type: object
      properties:
        nlpId:
          type: string
          description: Unique session identifier for maintaining context in future NLP requests.
          example: "d38a5bfc-3e8f-4a00-b9s7a-49fe545fa72b"
        nlpVersion:
          type: string
          description: The NLP model version used to process the prompt.
          example: "1"
        clientId:
          type: string
          description: The `clientId` of the client that the NLP prompt is for.
          example: "12345"
    NLPRequest:
      type: object
      description: Details of the Repliers API request generated by the NLP model.
      properties:
        url:
          type: string
          description: Formatted GET /listings URL ready for use.
          example: "https://api.repliers.io/listings?area=Toronto&city=Toronto&propertyType=Condo%20Apt&minBeds=1&neighborhood=Annex&garage=Underground"
        body:
          type: object
          description: Formatted POST /listings body ready for use.
          properties:
            imageSearchItems:
              type: array
              description: List of image search items.
              items:
                type: object
                properties:
                  type:
                    type: string
                    description: |
                      possible values `text` or `image`
                    example: "text"
                  value:
                    type: string
                    description: The text or image URL for the search item.
                    example: white kitchen
                  boost:
                    type: number
                    description: Boost value for the search item.
                    example: 1
        summary:
          type: string
          description: Summary of how the prompt was interpreted by NLP model.
          example: "Searching for a condominium apartment in Toronto with a minimum of 1 bedroom located in the Annex neighborhood. The property must have underground parking."
