openapi: 3.1.0
info:
  title: Places API
  version: 1.0.0
servers:
  - url: https://api.repliers.io
paths:
  /places:
    get:
      summary: Places
      description: Use this endpoint to retrieve relevant schools, parks, transit stops and safety places for a given latitude and longitude. This endpoint is useful to enrich property and neighborhood views with local places information.
      operationId: places
      parameters:
        - name: lat
          in: query
          description: The latitude of the point that you'd like to retrieve places data for.
          required: true
          schema:
            type: string
        - name: long
          in: query
          description: The longitude of the point that you'd like to retrieve places data for.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
        "400":
          description: "400"
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
